# Generated by Django 3.0.4 on 2020-12-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fp_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp_ID', models.IntegerField()),
                ('fp_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='geo_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('uniqueID', models.CharField(max_length=10)),
                ('latitudes', models.CharField(max_length=10)),
                ('longitudes', models.CharField(max_length=10)),
            ],
        ),
    ]
