# Generated by Django 3.1.5 on 2021-01-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fp_table',
        ),
        migrations.DeleteModel(
            name='geo_table',
        ),
    ]
