# Generated by Django 3.0.4 on 2020-12-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='command',
            field=models.CharField(default='0-0', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='0000', max_length=15),
        ),
    ]
