# Generated by Django 3.0.4 on 2020-12-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201224_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.TextField(default='----', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='vechile_number',
            field=models.CharField(default='----', max_length=15),
        ),
    ]
